server:
  port: 8081
spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: EcommerceSystem
      collection: inventory
  profiles:
    active: local
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
