server:
  port: 8081
  servlet:
    context-path: /inventory-service
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: EcommerceSystem
      collection: inventory
  profiles:
    active: local
logging:
  config: classpath:logback-spring.xml

